// export const locales = [
//     { country: 'AF', language: 'ps' }, { country: 'AF', language: 'uz' }, { country: 'AL', language: 'sq' },
//     { country: 'DZ', language: 'ar' }, { country: 'AD', language: 'ca' }, { country: 'AO', language: 'pt' },
//     { country: 'AI', language: 'en' }, { country: 'AG', language: 'en' }, { country: 'AR', language: 'es' },
//     { country: 'AM', language: 'hy' }, { country: 'AW', language: 'nl' }, { country: 'AU', language: 'en' },
//     { country: 'AT', language: 'de' }, { country: 'AZ', language: 'az' }, { country: 'BS', language: 'en' },
//     { country: 'BH', language: 'ar' }, { country: 'BD', language: 'bn' }, { country: 'BB', language: 'en' },
//     { country: 'BY', language: 'be' }, { country: 'BE', language: 'nl' }, { country: 'BZ', language: 'en' },
//     { country: 'BJ', language: 'fr' }, { country: 'BM', language: 'en' },
//     { country: 'BO', language: 'es' }, { country: 'BA', language: 'bs' }, { country: 'BW', language: 'en' },
//     { country: 'BR', language: 'pt' }, { country: 'VG', language: 'en' }, { country: 'BN', language: 'ms' },
//     { country: 'BG', language: 'bg' }, { country: 'BF', language: 'fr' }, { country: 'BI', language: 'fr' },
//     { country: 'KH', language: 'km' }, { country: 'CM', language: 'fr' }, { country: 'CA', language: 'en' },
//     { country: 'CV', language: 'pt' }, { country: 'KY', language: 'en' }, { country: 'CF', language: 'fr' },
//     { country: 'TD', language: 'fr' }, { country: 'CL', language: 'es' }, { country: 'CN', language: 'zh' },
//     { country: 'HK', language: 'zh' }, { country: 'MO', language: 'zh' }, { country: 'CO', language: 'es' },
//     { country: 'KM', language: 'ar' }, { country: 'CG', language: 'fr' }, { country: 'CD', language: 'fr' },
//     { country: 'CK', language: 'en' }, { country: 'CR', language: 'es' }, { country: 'CI', language: 'fr' },
//     { country: 'HR', language: 'hr' }, { country: 'CU', language: 'es' }, { country: 'CW', language: 'nl' },
//     { country: 'CY', language: 'el' }, { country: 'CZ', language: 'cs' }, { country: 'DK', language: 'da' },
//     { country: 'DJ', language: 'fr' }, { country: 'DM', language: 'en' }, { country: 'DO', language: 'es' },
//     { country: 'EC', language: 'es' }, { country: 'EG', language: 'ar' }, { country: 'SV', language: 'es' },
//     { country: 'GQ', language: 'es' }, { country: 'ER', language: 'ti' }, { country: 'EE', language: 'et' },
//     { country: 'ET', language: 'am' }, { country: 'FK', language: 'en' },
//     { country: 'FJ', language: 'en' }, { country: 'FI', language: 'fi' }, { country: 'FR', language: 'fr' },
//     { country: 'GF', language: 'fr' }, { country: 'PF', language: 'fr' }, { country: 'GA', language: 'fr' },
//     { country: 'GM', language: 'en' }, { country: 'GE', language: 'ka' }, { country: 'DE', language: 'de' },
//     { country: 'GH', language: 'en' }, { country: 'GI', language: 'en' }, { country: 'GR', language: 'el' },
//     { country: 'GD', language: 'en' }, { country: 'GP', language: 'fr' },
//     { country: 'GU', language: 'en' }, { country: 'GT', language: 'es' }, { country: 'GG', language: 'en' },
//     { country: 'GN', language: 'fr' }, { country: 'GW', language: 'pt' }, { country: 'GY', language: 'en' },
//     { country: 'HT', language: 'fr' }, { country: 'HN', language: 'es' }, { country: 'HU', language: 'hu' },
//     { country: 'IS', language: 'is' }, { country: 'IN', language: 'hi' }, { country: 'ID', language: 'id' },
//     { country: 'IR', language: 'fa' }, { country: 'IQ', language: 'ar' }, { country: 'IE', language: 'ga' },
//     { country: 'IM', language: 'en' }, { country: 'IL', language: 'he' }, { country: 'IT', language: 'it' },
//     { country: 'JM', language: 'en' }, { country: 'JP', language: 'ja' }, { country: 'JE', language: 'en' },
//     { country: 'JO', language: 'ar' }, { country: 'KZ', language: 'kk' }, { country: 'KE', language: 'sw' },
//     { country: 'KI', language: 'en' }, { country: 'KP', language: 'ko' }, { country: 'KR', language: 'ko' },
//     { country: 'KW', language: 'ar' }, { country: 'KG', language: 'ky' }, { country: 'LA', language: 'lo' },
//     { country: 'LV', language: 'lv' }, { country: 'LB', language: 'ar' }, { country: 'LS', language: 'en' },
//     { country: 'LR', language: 'en' }, { country: 'LY', language: 'ar' }, { country: 'LI', language: 'de' },
//     { country: 'LT', language: 'lt' }, { country: 'LU', language: 'lb' }, { country: 'MO', language: 'zh' }, { country: 'MK', language: 'mk' }, { country: 'MG', language: 'mg' },
//     { country: 'MW', language: 'en' }, { country: 'MY', language: 'ms' }, { country: 'MV', language: 'dv' }, { country: 'ML', language: 'fr' },
//     { country: 'MT', language: 'mt' }, { country: 'MQ', language: 'fr' }, { country: 'MR', language: 'ar' },
//     { country: 'MU', language: 'fr' }, { country: 'YT', language: 'fr' }, { country: 'MX', language: 'es' }, { country: 'FM', language: 'en' },
//     { country: 'MD', language: 'ro' }, { country: 'MC', language: 'fr' }, { country: 'MN', language: 'mn' }, { country: 'ME', language: 'sr' },
//     { country: 'MS', language: 'en' }, { country: 'MA', language: 'ar' }, { country: 'MZ', language: 'pt' }, { country: 'MM', language: 'my' },
//     { country: 'NA', language: 'en' }, { country: 'NP', language: 'ne' }, { country: 'NL', language: 'nl' },
//     { country: 'NC', language: 'fr' }, { country: 'NZ', language: 'en' }, { country: 'NI', language: 'es' }, { country: 'NE', language: 'fr' },
//     { country: 'NG', language: 'en' }, { country: 'NF', language: 'en' }, { country: 'MP', language: 'en' },
//     { country: 'NO', language: 'no' }, { country: 'OM', language: 'ar' }, { country: 'PK', language: 'ur' }, { country: 'PW', language: 'en' },
//     { country: 'PS', language: 'ar' }, { country: 'PA', language: 'es' }, { country: 'PG', language: 'en' }, { country: 'PY', language: 'es' },
//     { country: 'PE', language: 'es' }, { country: 'PH', language: 'en' }, { country: 'PN', language: 'en' }, { country: 'PL', language: 'pl' },
//     { country: 'PT', language: 'pt' }, { country: 'PR', language: 'es' }, { country: 'QA', language: 'ar' }, { country: 'RE', language: 'fr' },
//     { country: 'RO', language: 'ro' }, { country: 'RU', language: 'ru' }, { country: 'RW', language: 'rw' }, { country: 'BL', language: 'fr' },
//     { country: 'SH', language: 'en' }, { country: 'KN', language: 'en' }, { country: 'LC', language: 'en' }, { country: 'MF', language: 'fr' },
//     { country: 'PM', language: 'fr' }, { country: 'VC', language: 'en' }, { country: 'WS', language: 'sm' }, { country: 'SM', language: 'it' },
//     { country: 'ST', language: 'pt' }, { country: 'SA', language: 'ar' }, { country: 'SN', language: 'fr' }, { country: 'RS', language: 'sr' },
//     { country: 'SC', language: 'fr' }, { country: 'SL', language: 'en' }, { country: 'SG', language: 'en' }, { country: 'SX', language: 'nl' },
//     { country: 'SK', language: 'sk' }, { country: 'SI', language: 'sl' }, { country: 'SB', language: 'en' }, { country: 'SO', language: 'so' },
//     { country: 'ZA', language: 'zu' }, { country: 'GS', language: 'en' }, { country: 'SS', language: 'en' }, { country: 'ES', language: 'es' },
//     { country: 'LK', language: 'si' }, { country: 'SD', language: 'ar' }, { country: 'SR', language: 'nl' }, { country: 'SJ', language: 'no' },
//     { country: 'SZ', language: 'en' }, { country: 'SE', language: 'sv' }, { country: 'CH', language: 'de' }, { country: 'SY', language: 'ar' },
//     { country: 'TW', language: 'zh' }, { country: 'TJ', language: 'tg' }, { country: 'TZ', language: 'sw' }, { country: 'TH', language: 'th' },
//     { country: 'TL', language: 'pt' }, { country: 'TG', language: 'fr' },
//     { country: 'TT', language: 'en' }, { country: 'TN', language: 'ar' }, { country: 'TR', language: 'tr' }, { country: 'TM', language: 'tk' },
//     { country: 'TC', language: 'en' }, { country: 'TV', language: 'en' }, { country: 'UG', language: 'en' }, { country: 'UA', language: 'uk' },
//     { country: 'AE', language: 'ar' }, { country: 'GB', language: 'en' }, { country: 'US', language: 'en' }, { country: 'UM', language: 'en' },
//     { country: 'VI', language: 'en' }, { country: 'UY', language: 'es' }, { country: 'UZ', language: 'uz' },
//     { country: 'VA', language: 'it' }, { country: 'VE', language: 'es' }, { country: 'VN', language: 'vi' }, { country: 'WF', language: 'fr' },
//     { country: 'EH', language: 'ar' }, { country: 'YE', language: 'ar' }, { country: 'ZM', language: 'en' }, { country: 'ZW', language: 'en' }
//     ];
    export const availableLanguages = ["en", "no"];
    export const defaultLocale = 'en';
    export const ipAddressRegex = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;